sqlserver:
  host: ${SQLSERVER_HOST}
  port: ${SQLSERVER_PORT}
  database: ${SQLSERVER_DATABASE}
  user: ${SQLSERVER_USER}
  password: ${SQLSERVER_PASSWORD}
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

services:
  pyspark_pipeline:
    volumes:
      - ./spark-temp:/tmp/spark-temp

storage:
  bronze:
    path: "data/bronze"
    format: "delta"

  silver:
    path: "data/silver"
    format: "delta"

  gold:
    path: "data/gold"
    format: "delta"

tables:
  - name: compras_ordens_itens
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true

  - name: rel_compras_ordens_referenciadas_saldos
    schema: dbo
    load_type: incremental
    incremental_column: data_emissao
    incremental_strategy: merge
    merge_keys: ["id", "produto_id", "ordem_compra_id", "id_item", "empresa_id"]
    watermark: true

  - name: produtos
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true

  - name: pessoas
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true

  - name: compras_ordens
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true

  - name: pedidos_itens
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true

  - name: estoques
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true

  - name: pedidos
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true
    
  - name: produtos_estoques_movimentacoes
    schema: dbo
    load_type: incremental
    incremental_column: data_atualizado
    incremental_strategy: merge
    merge_keys: ["id"]
    watermark: true